### PR TITLE
fix escaped quoation mark not handled properly

### LINKED ISSUE #23: Escaped quotation mark not handled properly
The following:

```rust
let foobar = "foo bar";
xshell::cmd!("ls \"{foobar}\"");
```

fails with:

```
error[E0765]: unterminated double quote string
  --> websites/print_css/src/main.rs:90:29
   |
90 | ...                   xshell::cmd!("ls \"{foobar}\"");
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Adding a space after the last escaped quotation mark works:

```rust
let foobar = "foo bar";
xshell::cmd!("ls \"{foobar}\" ");
```

### PR DESCRIPTION
**Pull request by oberblastmeister**
fix #23.

This is because we were using `trim_matches`, which will trim repeatedly. This means that if we have a string `"ls \"asdf\""` is will trim 1 `"` at the beginning but *2* `"` at the end. Thus, the trimmed string will become `ls \"asdf\` which is unable to be parsed.

### CODE REVIEW

**Comment by oberblastmeister** [comment]
woops, I accidentally used my other branch when creating this one, sorry

File: tests/it/main.rs [hunk 1]
```diff
@@ -470,6 +470,16 @@ fn formatting() {
...
 }
 
+#[test]
+#[allow(unused_must_use)]
+fn string_escapes() {
+    setup();
+
+    cmd!("\"hello\"");
+    cmd!("\"\"\" asdf\" \"");
+    cmd!("\\\\\\\\\\\\\\\\\\\\\\\\\\");
```
Comment (matklad) [inline tests/it/main.rs:480]: Let's add some asserts here, I think the best would be to use `cmd.to_string()` to check this:

https://github.com/matklad/xshell/blob/69ce10674ad73380eef6a4b6f0797343c476296d/tests/it/main.rs#L81-L93

File: xshell-macros/src/lib.rs [hunk 2]
```diff
@@ -177,3 +183,21 @@ fn respan(ts: TokenStream, span: Span) -> TokenStream {
...
+    use TokenKind::*;
+
+    #[test]
+    fn double_quoted() {
+        let res = tokenize(r#"""asdf"""#).collect::<Result<Vec<Token<'_>>>>().unwrap();
+        eprintln!("res = {:?}", res);
+
+        assert_eq!(&*res, [Token { joined_to_prev: true, text: "\"asdf\"", kind: Word }])
+    }
+}
```
Comment (matklad) [inline xshell-macros/src/lib.rs:203]: Let's remove this test and rely only on the integration tests in it/main.rs

**Review by matklad — COMMENTED** [review]
:heart:

**Comment by matklad** [comment]
Strange, while I wasn't able to force-push to your previous PR, I've accidentally fixed this one, while recording instructions of how to do this :D 

Here's the sequence of command I used:

* add my repo as another remote (I named it "upstream")
* make sure that local master branch is in sync with  "upstream"
* noted the git hash of "fix quotes" commit
* make the `lexer` branch point at the synced master 
* re-applied the commit with cherry-pick

People learn differently, but for me https://jwiegley.github.io/git-from-the-bottom-up/ was instrumental in "getting" git. 

```
17:00:30|~/tmp
λ git clone git@github.com:oberblastmeister/xshell.git
Cloning into 'xshell'...
remote: Enumerating objects: 581, done.
remote: Counting objects: 100% (125/125), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 581 (delta 74), reused 87 (delta 52), pack-reused 456
Receiving objects: 100% (581/581), 908.59 KiB | 2.14 MiB/s, done.
Resolving deltas: 100% (295/295), done.

17:01:05|~/tmp
λ cd xshell/

17:01:07|~/tmp/xshell|master✓
λ git remote -v
origin	git@github.com:oberblastmeister/xshell.git (fetch)
origin	git@github.com:oberblastmeister/xshell.git (push)

17:01:14|~/tmp/xshell|master✓
λ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.

17:01:27|~/tmp/xshell|master✓
λ git remote add upstream git@github.com:matklad/xshell.git

17:01:42|~/tmp/xshell|master✓
λ git fetch upstream
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (3/3), done.
Unpacking objects: 100% (4/4), 1.20 KiB | 1.20 MiB/s, done.
remote: Total 4 (delta 1), reused 3 (delta 1), pack-reused 0
From github.com:matklad/xshell
 * [new branch]      master     -> upstream/master
 * [new branch]      rwdeadlock -> upstream/rwdeadlock
 * [new branch]      staging    -> upstream/staging

17:01:51|~/tmp/xshell|master✓
λ git reset --hard upstream/master
HEAD is now at 6eb60e1 Merge #31

17:02:12|~/tmp/xshell|master✓
λ git push origin master --force
^C⏎                                                                                                                                                
17:02:24|~/tmp/xshell|master✓
λ git push origin master --force
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:oberblastmeister/xshell.git
 ! [remote rejected] master -> master (permission denied)
error: failed to push some refs to 'github.com:oberblastmeister/xshell.git'

17:02:31|~/tmp/xshell|master✓
λ git switch lexer
Branch 'lexer' set up to track remote branch 'lexer' from 'origin'.
Switched to a new branch 'lexer'

17:02:40|~/tmp/xshell|lexer✓
λ git log -n 3
commit 0b27604c6f747ed92294c1dd44178607fbb4cb46 (HEAD -> lexer, origin/lexer)
Author: Brian Shu <littlebubu.shu@gmail.com>
Date:   Fri May 21 09:09:37 2021 -0400

    fix quoting issue

commit c876a3bcff0a1e6cd99b7c71849fce6dd92ec924
Author: Brian Shu <littlebubu.shu@gmail.com>
Date:   Thu May 20 15:48:00 2021 -0400

    removed panicking

commit fd9c7a53c7bc34eba0c69cd2547a75fe49301510
Author: Brian Shu <littlebubu.shu@gmail.com>
Date:   Thu May 20 10:55:05 2021 -0400

    added some more tests

17:02:45|~/tmp/xshell|lexer✓
λ git rev-parse HEAD
0b27604c6f747ed92294c1dd44178607fbb4cb46

17:02:52|~/tmp/xshell|lexer✓
λ git reset --hard master
HEAD is now at 6eb60e1 Merge #31

17:03:04|~/tmp/xshell|lexer✓
λ git log -n 3
commit 6eb60e1d93bd6f1e41061eb0c4aa59c9bdb222dc (HEAD -> lexer, upstream/staging, upstream/master, master)
Merge: 709c061 a04404d
Author: bors[bot] <26634292+bors[bot]@users.noreply.github.com>
Date:   Fri May 21 13:57:01 2021 +0000

    Merge #31
    
    31: Allow redirecting commands to /dev/null r=matklad a=matklad
    
    bors r+
    🤖
    
    Co-authored-by: Brian Shu <littlebubu.shu@gmail.com>

commit a04404d54b16474c4de6990449c15b64e309c4d2
Author: Brian Shu <littlebubu.shu@gmail.com>
Date:   Tue May 18 16:55:36 2021 -0400

    Allow redirecting commands to /dev/null

commit 709c06116c14b0326bd7456e5cedfb91686456e2 (tag: v0.1.12, origin/staging, origin/lexer_tests)
Merge: b541024 69ce106
Author: bors[bot] <26634292+bors[bot]@users.noreply.github.com>
Date:   Sun May 9 13:43:25 2021 +0000

    Merge #28
    
    28: Publish v0.1.12 r=matklad a=matklad
    
    bors r+
    🤖
    
    Co-authored-by: Aleksey Kladov <aleksey.kladov@gmail.com>

17:03:08|~/tmp/xshell|lexer✓
λ git cherry-pick 0b27604c6f747ed92294c1dd44178607fbb4cb46
[lexer 07ce159] fix quoting issue
 Author: Brian Shu <littlebubu.shu@gmail.com>
 Date: Fri May 21 09:09:37 2021 -0400
 2 files changed, 37 insertions(+), 3 deletions(-)

17:03:17|~/tmp/xshell|lexer✓
λ git log -n 3
commit 07ce1599199e0c401e078d29a9022ff14200c197 (HEAD -> lexer)
Author: Brian Shu <littlebubu.shu@gmail.com>
Date:   Fri May 21 09:09:37 2021 -0400

    fix quoting issue

commit 6eb60e1d93bd6f1e41061eb0c4aa59c9bdb222dc (upstream/staging, upstream/master, master)
Merge: 709c061 a04404d
Author: bors[bot] <26634292+bors[bot]@users.noreply.github.com>
Date:   Fri May 21 13:57:01 2021 +0000

    Merge #31
    
    31: Allow redirecting commands to /dev/null r=matklad a=matklad
    
    bors r+
    🤖
    
    Co-authored-by: Brian Shu <littlebubu.shu@gmail.com>

commit a04404d54b16474c4de6990449c15b64e309c4d2
Author: Brian Shu <littlebubu.shu@gmail.com>
Date:   Tue May 18 16:55:36 2021 -0400

    Allow redirecting commands to /dev/null

17:03:21|~/tmp/xshell|lexer✓
λ git push --force
Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 24 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (8/8), 1.14 KiB | 1.14 MiB/s, done.
Total 8 (delta 3), reused 4 (delta 1), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:oberblastmeister/xshell.git
 + 0b27604...07ce159 lexer -> lexer (forced update)
```

**Comment by oberblastmeister** [comment]
Thanks! So are we just using this branch as the fix?

**Comment by matklad** [comment]
yes, this branch should be good!

**Comment by matklad** [comment]
(but you probably need `git fetch && git reset --hard orgin/lexer` to sync your local branch with the one in your repo)

**Comment by oberblastmeister** [comment]
I was working on some double quoted string stuff. What would be the best way to do it? I was thinking maybe just a raw string or escapes, like

```rust
cmd!(r#"echo "hello {world}""#)
cmd!("echo \"hello {world}\"")
```

but the multiple quotes and escapes are kind of confusing.

Can we do idents like this

```rust
cmd!(echo "hello {world}" another)
```

**Comment by matklad** [comment]
The semantics we want here is that of usual Rust literals. That means that we need to re-implement our own escaping the way rustc itself does it. See also https://internals.rust-lang.org/t/getting-value-out-of-proc-macro-literal/14140 (xshell was a motivation for that post).

**Comment by oberblastmeister** [comment]
That makes sense. So for example [here](https://github.com/matklad/xshell/blob/6eb60e1d93bd6f1e41061eb0c4aa59c9bdb222dc/xshell-macros/src/lib.rs#L28) we would have to also check if the string has a `b` or `r`, or some hashes?

**Comment by matklad** [comment]
Right. And we should error on `b`, don't process `r`, and process escapes sequences in usual literals. I don't think we should go as far as supporting unicode escapes and such, but `\'`, `\\`, `\"`, `\n` should be supported.

File: tests/it/main.rs [hunk 3]
```diff
@@ -470,6 +470,15 @@ fn formatting() {
     cmd!("cargo fmt --all -- --check").run().unwrap()
 }
 
+#[test]
+fn string_escapes() {
+    setup();
+
+    assert_eq!(cmd!("\"hello\"").to_string(), "\"hello\"");
+    assert_eq!(cmd!("\"\"\" asdf\" \"").to_string(), "\"\"\" asdf\" \"");
+    assert_eq!(cmd!("\\\\\\\\\\\\\\\\\\\\\\\\\\").to_string(), "\\\\\\\\\\\\\\\\\\\\\\\\\\");
```
Comment (matklad) [inline tests/it/main.rs:479]: Let's use the raw string literal syntax on the right hand side here `r##""""asdf""""##` to make this more readable
