### PR TITLE
Fix GSL with many readers

### LINKED ISSUE #35: Doing xshell::pushd with a directory created with xshell::mktemp_d panics
It seems like an obvious use but I'm probably missing something. Is this behavior intended? 

```rust
fn main() {
    println!(
        "Current working directory: {}",
        xshell::cwd().unwrap().display()
    );

    let tmp = xshell::mktemp_d().unwrap();

    println!("Created temporary directory: {}", tmp.path().display());

    // Enter directory in child block so pushd guard is dropped before tmp
    {
        let _cwd = xshell::pushd(tmp.path()).unwrap();

        println!(
            "Current working directory: {}",
            xshell::cwd().unwrap().display()
        );
    }
}
```
Gives:

```
Current working directory: /path/to/example/
Created temporary directory: /tmp/xshell-tmp-dir-0
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: calling write() with an active read guard on the same thread would deadlock', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/xshell-0.1.14/src/gsl.rs:44:13
```

### PR DESCRIPTION
**Pull request by azdavis**
Close #35.

The issue there was that we weren't correctly decrementing the number of readers in the `CACHE` when dropping a second read guard.

I added some new tests, including the failing example in the issue (now passes).

Also includes other misc fixes.

### CODE REVIEW

File: src/gsl.rs [hunk 1]
```diff
@@ -28,24 +28,34 @@ pub(crate) struct Guard(Option<Repr>);
 
 #[derive(Debug)]
 enum Repr {
-    Read(RwLockReadGuard<'static, ()>),
+    Read(Option<RwLockReadGuard<'static, ()>>),
     Write(RwLockWriteGuard<'static, ()>),
 }
 
+thread_local! {
+    static CACHE: Cell<Cache> = Cell::new(Cache::Read(0));
```
Comment (matklad) [inline src/gsl.rs:36]: :+1: for moving this up! "This module has ambient global state" is a pretty important bit of info, and it should be clearly visible!

**Review by matklad — APPROVED** [review]
Looks reasonable to me!

Could you update version in Cargo.lock to get this published?

File: src/gsl.rs (hunk 1 above)
Comment (azdavis) [reply src/gsl.rs:36]: Yeah I thought about not doing this since it's not "relevant" to the PR itself, but since the cache is used a lot in the read and write functions I thought it'd be better to show its definition sooner.
